[target.aarch64-linux-android]
# image = "ghcr.io/cross-rs/aarch64-linux-android:edge"
image = "waterbang/aarch64-linux-android:v1"

[container.opts]
--network = "host"

[build.env]
passthrough = [
  "V8_FROM_SOURCE",
  "SCCACHE_ERROR_LOG",
  "SCCACHE_LOG",
  "SCCACHE_DIR",
  "SCCACHE_IDLE_TIMEOUT",
]
