[target.aarch64-linux-android]
image = "aarch64-android-rusty-v8:v1"

[build.env]
passthrough = [
  "V8_FROM_SOURCE",
  "SCCACHE_ERROR_LOG",
  "SCCACHE_LOG",
  "SCCACHE_DIR",
  "SCCACHE_IDLE_TIMEOUT",
  "NINJA",
  "GN"
]
