FROM ghcr.io/cross-rs/aarch64-linux-android:edge

RUN apt-get install software-properties-common -y && add-apt-repository ppa:deadsnakes/ppa 

RUN  apt-get install python3.10 -y

RUN mv /usr/bin/python3 /usr/bin/python




